name: grammar_ninja
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - ca-certificates
  - openssl
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - certifi
  - pyarrow
  - lightning
  - ipython
  - jupyter
  - ipykernel
  - pip
  - pip:
    - accelerate
    - bitsandbytes
    - transformers
    - huggingface-hub
    - hf_transfer
    - peft
    - wandb
    - spacy