name: grammar_ninja
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - ca-certificates
  - openssl
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - certifi
  - pyarrow
  - lightning
  - ipython
  - jupyter
  - ipykernel
  - pip
  - pip:
    - accelerate==0.25.0
    - aiohttp==3.9.1
    - aiosignal==1.3.1
    - annotated-types==0.6.0
    - anyio==3.7.1
    - appdirs==1.4.4
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==2.4.1
    - async-lru==2.0.4
    - async-timeout==4.0.3
    - attrs==23.1.0
    - Babel==2.14.0
    - backoff==2.2.1
    - beautifulsoup4==4.12.2
    - bitsandbytes==0.41.3.post2
    - bleach==6.1.0
    - blessed==1.19.1
    - blis==0.7.11
    - Brotli==1.0.9
    - build==1.0.3
    - CacheControl==0.13.1
    - cached-property==1.5.2
    - catalogue==2.0.10
    - certifi==2023.11.17
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - cleo==2.1.0
    - click==8.1.7
    - cloudpathlib==0.16.0
    - colorama==0.4.6
    - comm==0.1.4
    - confection==0.1.4
    - contourpy==1.2.0
    - crashtest==0.4.1
    - croniter==1.4.1
    - cryptography==41.0.7
    - cycler==0.12.1
    - cymem==2.0.8
    - datasets==2.15.0
    - dateutils==0.6.12
    - debugpy==1.8.0
    - decorator==5.1.1
    - deepdiff==6.7.1
    - defusedxml==0.7.1
    - dill==0.3.7
    - distlib==0.3.8
    - docker-pycreds==0.4.0
    - dulwich==0.21.7
    - en-core-web-md==3.7.1
    - en-core-web-sm==3.7.1
    - entrypoints==0.4
    - exceptiongroup==1.2.0
    - executing==2.0.1
    - fastapi==0.105.0
    - fastjsonschema==2.19.0
    - filelock==3.13.1
    - fonttools==4.46.0
    - fqdn==1.5.1
    - frozenlist==1.4.0
    - fsspec==2023.10.0
    - gitdb==4.0.11
    - GitPython==3.1.40
    - gmpy2==2.1.2
    - grammar-ninja==0.0.1
    - h11==0.14.0
    - hf_transfer==0.1.4
    - huggingface-hub==0.19.4
    - idna==3.6
    - importlib-metadata==7.0.0
    - importlib-resources==6.1.1
    - inquirer==3.1.4
    - installer==0.7.0
    - ipykernel==6.26.0
    - ipython==8.18.1
    - ipywidgets==8.1.1
    - isoduration==20.11.0
    - itsdangerous==2.1.2
    - jaraco.classes==3.3.0
    - jedi==0.19.1
    - jeepney==0.8.0
    - Jinja2==3.1.2
    - joblib==1.3.2
    - json5==0.9.14
    - jsonpointer==2.4
    - jsonschema==4.20.0
    - jsonschema-specifications==2023.11.2
    - jupyter==1.0.0
    - jupyter_client==8.6.0
    - jupyter-console==6.6.3
    - jupyter_core==5.5.0
    - jupyter-events==0.9.0
    - jupyter-lsp==2.2.1
    - jupyter_server==2.12.1
    - jupyter_server_terminals==0.5.0
    - jupyterlab==4.0.9
    - jupyterlab_pygments==0.3.0
    - jupyterlab_server==2.25.2
    - jupyterlab-widgets==3.0.9
    - keyring==24.3.0
    - kiwisolver==1.4.5
    - langcodes==3.3.0
    - lightning==2.1.2
    - lightning-cloud==0.5.39
    - lightning-utilities==0.10.0
    - markdown-it-py==3.0.0
    - MarkupSafe==2.1.3
    - matplotlib==3.8.2
    - matplotlib-inline==0.1.6
    - mdurl==0.1.0
    - mistune==3.0.2
    - more-itertools==10.1.0
    - mpmath==1.3.0
    - msgpack==1.0.7
    - multidict==6.0.4
    - multiprocess==0.70.15
    - munkres==1.1.4
    - murmurhash==1.0.10
    - nbclient==0.8.0
    - nbconvert==7.12.0
    - nbformat==5.9.2
    - nest-asyncio==1.5.8
    - networkx==3.2.1
    - notebook==7.0.6
    - notebook_shim==0.2.3
    - numpy==1.26.2
    - ordered-set==4.1.0
    - orjson==3.9.10
    - overrides==7.4.0
    - packaging==23.2
    - pandas==2.1.4
    - pandocfilters==1.5.0
    - parso==0.8.3
    - patsy==0.5.4
    - peft==0.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - Pillow==9.4.0
    - pip==23.3.1
    - pkginfo==1.9.6
    - pkgutil_resolve_name==1.3.10
    - platformdirs==3.11.0
    - ply==3.11
    - poetry==1.7.1
    - poetry-core==1.8.1
    - poetry-plugin-export==1.6.0
    - preshed==3.0.9
    - prometheus-client==0.19.0
    - prompt-toolkit==3.0.42
    - protobuf==4.25.1
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==12.0.1
    - pyarrow-hotfix==0.6
    - pycparser==2.21
    - pydantic==2.1.1
    - pydantic_core==2.4.0
    - Pygments==2.17.2
    - PyJWT==2.8.0
    - pyparsing==3.1.1
    - pyproject_hooks==1.0.0
    - PyQt5==5.15.9
    - PyQt5-sip==12.12.2
    - PySocks==1.7.1
    - python-dateutil==2.8.2
    - python-editor==1.0.4
    - python-json-logger==2.0.7
    - python-multipart==0.0.6
    - pytorch-lightning==2.1.2
    - pytz==2023.3.post1
    - PyYAML==6.0.1
    - pyzmq==25.1.2
    - qtconsole==5.5.1
    - QtPy==2.4.1
    - rapidfuzz==3.5.2
    - readchar==4.0.5.dev0
    - referencing==0.32.0
    - regex==2023.10.3
    - requests==2.31.0
    - requests-toolbelt==1.0.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==13.7.0
    - rpds-py==0.13.2
    - safetensors==0.4.1
    - scikit-learn==1.3.2
    - SciPy==1.11.4
    - seaborn==0.13.0
    - SecretStorage==3.3.3
    - Send2Trash==1.8.2
    - sentry-sdk==1.39.1
    - setproctitle==1.3.3
    - setuptools==68.2.2
    - shellingham==1.5.4
    - sip==6.7.12
    - six==1.16.0
    - smart-open==6.4.0
    - smmap==5.0.1
    - sniffio==1.3.0
    - soupsieve==2.5
    - spacy==3.7.2
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    - srsly==2.4.8
    - stack-data==0.6.2
    - starlette==0.27.0
    - starsessions==1.3.0
    - statsmodels==0.14.1
    - sympy==1.12
    - terminado==0.18.0
    - thinc==8.2.2
    - threadpoolctl==3.2.0
    - tinycss2==1.2.1
    - tokenizers==0.15.0
    - toml==0.10.2
    - tomli==2.0.1
    - tomlkit==0.12.3
    - torch==2.1.2
    - torchaudio==2.1.2
    - torchmetrics==1.2.1
    - torchvision==0.16.2
    - tornado==6.3.3
    - tqdm==4.66.1
    - traitlets==5.14.0
    - transformers==4.36.1
    - triton==2.1.0
    - trove-classifiers==2023.11.29
    - typer==0.9.0
    - types-python-dateutil==2.8.19.14
    - typing_extensions==4.9.0
    - typing-utils==0.1.0
    - tzdata==2023.3
    - unicodedata2==15.1.0
    - uri-template==1.3.0
    - urllib3==2.1.0
    - uvicorn==0.24.0.post1
    - virtualenv==20.25.0
    - wandb==0.16.1
    - wasabi==1.1.2
    - wcwidth==0.2.12
    - weasel==0.3.4
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.7.0
    - websockets==12.0
    - wheel==0.42.0
    - widgetsnbextension==4.0.9
    - xxhash==3.4.1
    - yarl==1.9.4
    - zipp==3.17.0